### ISSUE TITLE
Can you release pretrained models?

### ISSUE THREAD

**Issue by AtlantixJJ** [nv-tlabs/datasetGAN_release#31] opened 2021-09-20 10:03 UTC
Hi, could you please release the pretrained semantic segmentation networks?

Please understand, if your paper is going to be cited and compared, either you should provide your test data, or you should release your pre-trained weights.

Thank you.

**Comment by arieling** [comment] 2021-09-20 21:57
Hi, Thank you for interested in our work.

We released interpreter checkpoints at https://drive.google.com/drive/u/1/folders/1Hhu8aGxbnUtK-yHRD9BXZ3gn3bNNmsGi. Deeplab can't be released due to strict license constrain. If you follow the steps stated in the README, you can reproduce exactly the same table stated in the Inference section. Let me know if you run into any issues.

We also released test data we have the license to release at https://drive.google.com/drive/u/1/folders/1Oa9XpyKnRSN5s9-ab2-5j3wvH374JOu8.  
Furthermore, A larger-scale benchmark on ade-car 32 classes and celeb faces 34 classes testing set will be released soon.


Please reopen the issue if you have more questions!

**Closed as completed by arieling** 2021-09-20 21:57 UTC
